# version: '3.8'

services:
  app:
    build:
      context: .
    container_name: pics
    ports:
      - "8080:80"
    volumes:
      - .public:/var/www/html
    env_file:
      - .env  # Load environment variables from your .env file
    networks:
      - app-network

networks:
  app-network:
